package com.approachingpi.mobicents.demo.model;
// Generated Sep 21, 2009 8:40:41 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;
import static javax.persistence.GenerationType.IDENTITY;

import org.hibernate.validator.Length;

/**
 * Call generated by hbm2java
 */
@Entity
@Table(name = "phoneCall")
public class PhoneCall implements java.io.Serializable {

	private int id;
	private Date dateStart;
	private Date dateEnd;
	private String fromAddress;
	private String toAddress;
	private String dtmf;
	private Set<Session> sessions = new HashSet<Session>(0);

	public PhoneCall() {
	}

	public PhoneCall(int id) {
		this.id = id;
	}
	public PhoneCall(int id, Date dateStart, Date dateEnd, String from, String to,
			String dtmf, Set<Session> sessions) {
		this.id = id;
		this.dateStart = dateStart;
		this.dateEnd = dateEnd;
		this.fromAddress = from;
		this.toAddress = to;
		this.dtmf = dtmf;
		this.sessions = sessions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateStart", length = 19)
	public Date getDateStart() {
		return this.dateStart;
	}

	public void setDateStart(Date dateStart) {
		this.dateStart = dateStart;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateEnd", length = 19)
	public Date getDateEnd() {
		return this.dateEnd;
	}

	public void setDateEnd(Date dateEnd) {
		this.dateEnd = dateEnd;
	}

	@Column(name = "fromAddress", length = 100)
	@Length(max = 100)
	public String getFromAddress() {
		return this.fromAddress;
	}

	public void setFromAddress(String from) {
		this.fromAddress = from;
	}

	@Column(name = "toAddress", length = 100)
	@Length(max = 100)
	public String getToAddress() {
		return this.toAddress;
	}

	public void setToAddress(String to) {
		this.toAddress = to;
	}

	@Column(name = "dtmf", length = 300)
	@Length(max = 300)
	public String getDtmf() {
		return this.dtmf;
	}

	public void setDtmf(String dtmf) {
		this.dtmf = dtmf;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "call")
	public Set<Session> getSessions() {
		return this.sessions;
	}

	public void setSessions(Set<Session> sessions) {
		this.sessions = sessions;
	}

}
