package com.approachingpi.mobicents.demo.model;
// Generated Sep 21, 2009 8:40:41 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import javax.persistence.*;
import static javax.persistence.GenerationType.IDENTITY;

/**
 * Session generated by hbm2java
 */
@Entity
@Table(name = "session")
public class Session implements java.io.Serializable {

	private int id;
	private PhoneCall call;
	private Date dateCreated;
	private Date dateValidated;

	public Session() {
	}

	public Session(int id) {
		this.id = id;
	}
	public Session(int id, PhoneCall call, Date dateCreated, Date dateValidated) {
		this.id = id;
		this.call = call;
		this.dateCreated = dateCreated;
		this.dateValidated = dateValidated;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "callId")
	public PhoneCall getCall() {
		return this.call;
	}

	public void setCall(PhoneCall call) {
		this.call = call;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateCreated", length = 19)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateValidated", length = 19)
	public Date getDateValidated() {
		return this.dateValidated;
	}

	public void setDateValidated(Date dateValidated) {
		this.dateValidated = dateValidated;
	}

}
